# Spring Datasource Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookservice  
    username: postgres 
    password: admin     
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  
  application:
    name: book-service  

# Server Configuration
server:
  port: 8082 

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-expiration-duration-in-seconds: 30  # Lease expiration duration
    lease-renewal-interval-in-seconds: 15  # Lease renewal interval
