spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice  # Database URL
    username: postgres  # Database username
    password: admin     # Database password
  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the database schema
    show-sql: true      # Show SQL queries in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Hibernate dialect for PostgreSQL
  application:
    name: user-service  # Name of the application
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/  # Corrected URL format
        register-with-eureka: true
        fetch-registry: true
      instance:
        lease-expiration-duration-in-seconds: 30  # Lease expiration duration
        lease-renewal-interval-in-seconds: 15  # Lease renewal interval

server:
  port: 8083 # Port on which the service will run
